server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.4.1"
      repository: "https://maven.lavalink.dev/releases"
  pluginsDir: "./plugins"
  server:
    password: "${LAVALINK_PASSWORD:youshallnotpass}"
    sources:
      youtube: false # handled by plugin
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      timescale: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    playerUpdateInterval: 5

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    region: "US"
    language: "en"
    clients:
      - ANDROID_VR
      - ANDROID_TESTSUITE
      - TVHTML5EMBEDDED
      - TVHTML5
      - MUSIC
    oauth:
      enabled: true
      refreshToken: "${YOUTUBE_REFRESH_TOKEN:}"
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
      - "ytmsearch:%QUERY%"
    sources:
      spotify: true
      appleMusic: false
      deezer: false
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID:}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET:}"
      playlistLoadLimit: 50
      albumLoadLimit: 50

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO

metrics:
  prometheus:
    enabled: false
